### ISSUE TITLE
Parsing error: Unexpected token import

### ISSUE THREAD

**Issue by aliirfan781** [CodeDredd/pinia-orm#1665] opened 2023-09-15 12:07 UTC
### Environment

Node.js Version:  v18.15.0
Quasar Version: @quasar/cli v2.2.3
Build Tool: Webpack
Operating System: Windows 11

### Reproduction

package.json
{
  "name": "quasar-project",
  "version": "0.0.1",
  "description": "A Quasar Project",
  "productName": "Quasar App",
  "author": "Ali Irfan <aliirfankhan781@gmail.com>",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "format": "prettier --write \"**/*.{js,vue,scss,html,md,json}\" --ignore-path .gitignore",
    "test": "echo \"No test specified\" && exit 0",
    "dev": "quasar dev",
    "build": "quasar build"
  },
  "dependencies": {
    "@quasar/extras": "^1.16.4",
    "axios": "^1.2.1",
    "pinia": "^2.0.11",
    "pinia-orm": "^1.6.7",
    "quasar": "^2.6.0",
    "vue": "^3.0.0",
    "vue-i18n": "^9.0.0",
    "vue-router": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.22.19",
    "@babel/preset-env": "^7.22.15",
    "@intlify/vite-plugin-vue-i18n": "^3.3.1",
    "@quasar/app-vite": "^1.3.0",
    "autoprefixer": "^10.4.2",
    "eslint": "^8.10.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^9.0.0",
    "postcss": "^8.4.14",
    "prettier": "^2.5.1"
  },
  "engines": {
    "node": "^18 || ^16 || ^14.19",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}

### Describe the bug

I am building a project in quasar framework and using pinia ORM in it. I am facing this error inside my model Doctor.js
this is the path inside the file and error exists inside the line "static entity ='doctors'" and they say "=" unexpected token
// Doctor Model

import { Model } from "pinia-orm";

export default class Doctor extends Model {
  // entity is a required property for all models.
  static entity = "doctors";

  static fields() {
    return {
      id: this.uid(),
      name: this.string(""),
      email: this.string(""),
      mobile: this.string(""),
      city: this.string(""),
      pictureUrl: this.string(""),
    };
  }
}

**Comment by CodeDredd** [comment] 2023-09-15 15:26
Would you please provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by aliirfan781** [comment] 2023-09-16 10:46
I have edited my issue. The error is in model class. I am beginner but I have figured it out that it is due to ecma script version. Could you help me to figure out how to resolve it.

**Comment by CodeDredd** [comment] 2023-09-17 06:38
@aliirfan781 Thanks for providing more info. But i need more information than that to understand the problem. It wouuld be also enough to link a working repository where also functional code is to reproduce the error.

**Comment by AlexZion** [comment] 2023-10-20 10:42
I'm facing the same problem and the wired part is that I have two similar project with the exact same store settings. In the first it works as expected while in the second there is no way to make it works, even using the same model used on the first project. 
I'll try understand what's going on, but for now I didn't find any relevant difference between the first and the second project.

**Comment by CodeDredd** [comment] 2024-05-06 09:44
Closing it because its seems no issue anymore.

**Closed by CodeDredd** 2024-05-06 09:44 UTC
Labels: quasar, needs reproduction, pending triage
