### ISSUE TITLE
Repository find() method is missing from type declarations

### ISSUE THREAD

**Issue by DaRosenberg** [CodeDredd/pinia-orm#1884] opened 2024-07-04 13:14 UTC
### Reproduction

N/A

### Describe the bug

The docs indicate that there is a `find()` method directly on the repository:
https://pinia-orm.codedredd.de/api/query/find

It does also work at runtime.

But in the type declarations, the `find()` method is only available on the query interface:
`repo.query().find(id)`

It seems to be the type declarations are wrong and the repository interface should have the `find()` method on it (since it evidently does work at runtime)

**Comment by CodeDredd** [comment] 2024-07-04 13:51
This is not a bug but a feature 😉 . To reduce code i tried to use a proxy to query the same functions which are in query. The only thing that was wrong is the type. But this is already fixed in this issue #1863 if you use the edge release channel.

I am also soon releasing 1.9.2. So if you wait i bit you don't need to checkout the release edge channel.

**Closed by CodeDredd** 2024-07-04 13:51 UTC
Labels: pending triage

**Comment by DaRosenberg** [comment] 2024-07-04 13:59
Excellent, thanks @CodeDredd
